### PR TITLE
also fix Host._serializer being set twice (invalid value used to initialize ParameterTransferHelper)

### PR DESCRIPTION
**Pull request by xen2**
I forgot to update the `Host` too in the previous PR...

### CODE REVIEW

**Comment by tylerje** [comment]
Let's get some unit tests added to test all the chsnges, including the previous PR.

**Comment by xen2** [comment]
Sorry, forgot about this PR, here you go.
It includes unit test.
Note that it was already mitigated with #29 but `_serializer` was still being set twice to the same value so I still backported the remaining changes to master.

**Comment by xen2** [comment]
PS: It would be great if a new release could be done with those fixes, thanks!

**Comment by tylerje** [comment]
Good work. Thank you.

**Pull request merged**
