### PR TITLE
Type Mapping #2

### LINKED ISSUE #36: typeConfigName.ToType returns null in a framework client to netcore server
image
image

type is null but the object that was deserialized is already translated to the correct type, System.Private.Uri looks to be the netcore type configuration name instead of the framework type configuration name.

Type.GetType("System.Uri[], System.Private.Uri") | null 
obj.GetType().Assembly | {System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089} 
typeConfigName | System.Uri[], System.Private.Uri

if typeConfigName was set to "System.Uri[], System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089". the type would not be null.

I wonder if this is the reason why you have not strong named service wire. but not having a strong name limits the library to applications that do not use strong names. would it break anything to return the object without converting if the type is null?

would this address the situation:
image

### PR DESCRIPTION
**Pull request by kccarter76**
resolves #36

I have removed nerd bank it was not required for this to work.

### CODE REVIEW

**Comment by kccarter76** [comment]
if there is anything you want to change about this pull request. we can make active changes without closing the request.

**Comment by tylerje** [comment]
I'll review when I can think better. Sadly I'm I'll and running a fever, so it could be a while.

**Comment by kccarter76** [comment]
that is fine, it is a scary time to be sick with something. I have had a few scares myself.

**Comment by tylerje** [comment]
For now, until we solve it, you can convert the Uri to a string and back. It's probably about the same as serializing the whole Uri.

**Comment by kccarter76** [comment]
I realize, the existing code you have in place for type mapping is not ideal, but you told me this is a stateless implementation between the client and the server. unless both sides now about it there will be a mismatched type. that being said, I have successfully configured a pipe between framework and netcore for the purpose of T4 templating generation in visual studio, using service wire. the only caveat being is that I need the code that this pull request implements to make it work.

if you do not want to merge this pull request, let me know and I will fork service wire and deploy it in the SubSonic.Core project under the name of ServiceWire and in full compliance with the Apache 2.0 license.

**Comment by tylerje** [comment]
But I'm still not happy with that approach. I'm not liking the approach of actual mapping in the library either. We'll all be one big happy .NET 5 at some point, and .NET Framework will eventually end. I realize this is down the road, but I don't want to create a complex solution to a problem that is not common for users of the library. I suggest you fork and modify as you please for your use and approach.

**Comment by kccarter76** [comment]
the honest truth about being a happy net 5 family is that it's 10 to 30 + years down the line. I know companies that still need cobol and delphi 6 developers just for maintenance. The company I work for will eventually move to net 5 but it most likely 5 years out before that starts and another 15 before complete conversion.

**Pull request closed without merging**
